auth:
  basePath: "127.0.0.1:9000"
  signupPath: /identity
  signinPath: /session/new
  validationPath: /session/validate
  signoutPath: /session/destroy
  internal:
    idHeader: "x-user-id" # Should not be a invalid and/or canonical/standard HTTP header

gateway:
  schema: https                         # http | https
  tlsCertFile: ./example.com+5.pem      # Required only in case of "schema = https"
  tlsKeyFile: ./example.com+5-key.pem   # Required only in case of "schema = https"
  port: 8080

matchPaths:
  - value: "/profiles"
    targetHost: "profileservice"
    targetPort: 3001
  - value: "/galleries"
    targetHost: "galleryservice"
    targetPort: 3002
  - value: /items
    targetHost: 127.0.0.1
    targetPort: 8000
